module.exports = {
    login: () => {},
    list: (req, res) => {
        const {} = req.body;
        //console.log(JSON.stringify(req.body, null, 2));

        return res.send({
            teams: [
                "Fenerbahçe",
                "Galatasaray",
                "Beşiktaş",
                "Adana Demirspor",
                "Trabzonspor",
                "Başakşehir",
                "Konyaspor",
                "Kayserispor",
                "Ümraniyespor",
                "İstanbulspor",
                "Giresunspor",
                "Hatayspor",
                "Sivasspor",
                "Ankaragücü",
                "Fatih Karagümrük",
                "Antalyaspor",
                "Kasımpaşa",
                "Gaziantep Futbol Kulübü",
                "Alanyaspor",
            ],
        });
    },
    teamsList: (req, res) => {
        return res.send({
            teams: [
                {
                    name: "Fenerbahçe",
                    coach: "Jorge Jesus",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/8/86/Fenerbah%C3%A7e_SK.png?20211002193712",
                    alt: "fb",
                },
                {
                    name: "Galatasaray",
                    coach: "Okan Buruk",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Galatasaray_Sports_Club_Logo.png/822px-Galatasaray_Sports_Club_Logo.png",
                    alt: "gs",
                },
                {
                    name: "Beşiktaş",
                    coach: "Şenol Güneş",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/commons/0/08/Be%C5%9Fikta%C5%9F_Logo_Be%C5%9Fikta%C5%9F_Amblem_Be%C5%9Fikta%C5%9F_Arma.png",
                    alt: "bjk",
                },
                {
                    name: "Trabzonspor",
                    coach: "Abdullah Avcı",
                    numPlayers: 32,
                    anthem: "https://www.trabzonspor.org.tr/download/resources/logo_6367234456_-1x-1_false.png",
                    alt: "asd",
                },
                {
                    name: "Adana Demirspor",
                    coach: "Vincenzo Montella",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/5/5f/Adanademirspor.png?20101106185724",
                    alt: "asd",
                },
                {
                    name: "Konyaspor",
                    coach: "İlhan Palut",
                    numPlayers: 27,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/archive/4/41/20220809170232%21Konyaspor_1922.png",
                    alt: "asd",
                },
                {
                    name: "Kayserispor",
                    coach: "Çağdaş Atan",
                    numPlayers: 32,
                    anthem: "https://tmssl.akamaized.net/images/wappen/head/3205.png?lm=1520239955",
                    alt: "asd",
                },
                {
                    name: "Ümraniyespor",
                    coach: "Recep Ucar",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/7/75/%C3%9Cmraniyespor_Logosu.png",
                    alt: "asd",
                },
                {
                    name: "İstanbulspor",
                    coach: "Osman Zeki Korkmazv",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/e/ed/IstanbulsporAS.png",
                    alt: "asd",
                },
                {
                    name: "Giresunspor",
                    coach: "Hakan Keleş",
                    numPlayers: 27,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/c/c1/Giresunspor.png",
                    alt: "asd",
                },
                {
                    name: "Hatayspor",
                    coach: "Volkan Demirel",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/0/08/Hatayspor.png",
                    alt: "asd",
                },
                {
                    name: "Sivasspor",
                    coach: "Vincenzo Montella",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Sivasspor_logo.svg/1200px-Sivasspor_logo.svg.png",
                    alt: "asd",
                },
                {
                    name: "Ankaragücü",
                    coach: "Ömer Erdoğan",
                    numPlayers: 32,
                    anthem: "https://ankaragucu.org.tr/wp-content/uploads/2018/06/MKE_Ankarag%C3%BCc%C3%BC_logo.png",
                    alt: "asd",
                },
                {
                    name: "Fatih Karagümrük",
                    coach: "Andrea Pirlo",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/9/90/Fatihkaragumruk.png",
                    alt: "asd",
                },
                {
                    name: "Antalyaspor",
                    coach: "Nuri Şahin",
                    numPlayers: 29,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/b/b9/Antalyaspor_logo.png",
                    alt: "asd",
                },
                {
                    name: "Kasımpaşa",
                    coach: "Şenol Can",
                    numPlayers: 29,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/6/68/Kasimpasa_2012.png",
                    alt: "asd",
                },
                {
                    name: "Gaziantep Futbol Kulübü",
                    coach: "Vincenzo Montella",
                    numPlayers: 22,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/1/18/Gaziantep_FK.png",
                    alt: "asd",
                },
                {
                    name: "Alanyaspor",
                    coach: "Francesco Farioli",
                    numPlayers: 32,
                    anthem: "https://upload.wikimedia.org/wikipedia/tr/2/29/Alanyaspor_logo.png",
                    alt: "asd",
                },
                {
                    name: "Başakşehir",
                    coach: "Emre Belözoğlu",
                    numPlayers: 31,
                    anthem: "http://www.futbollogo.com/resimler/logolar/istanbulbasaksehir.png",
                    alt: "asd",
                },
            ],
        });
    },
    update: () => {},
    remove: () => {},
};
